export const metadata = {
    title: 'Our Work',
    description: 'Generated by create next app',
}

export default function Page() {
    return <main>
        <h1>Hello, Our Work Page!</h1>
    </main>
  }