import OurWorkGallery from "../components/our-work/OurWorkGallery"
import OurWorkHero from "../components/our-work/OurWorkHero"

export const metadata = {
    title: 'Our Work',
    description: 'Generated by create next app',
}

export default function Page() {
    return <main>
        <OurWorkHero />
        <OurWorkGallery />
    </main>
  }