export const metadata = {
    title: 'Why Us',
    description: 'Generated by create next app',
}

export default function Page() {
    return <main>
        <h1>Hello, Why Us Page!</h1>
    </main>
  }