import AboutFAQs from "@/app/components/about/AboutFAQs"
import AboutHero from "@/app/components/about/AboutHero"
import OurStory from "@/app/components/about/OurStory"
import LightCTA from "@/app/components/global/LightCTA"
import OurTeam from "@/app/components/global/OurTeam"
import SplitContact from "@/app/components/global/SplitContact"

export const metadata = {
    title: 'About us',
    description: 'Generated by create next app',
}

export default function Page() {
    return <main>
        <AboutHero  />
        <OurStory />
        <OurTeam />
        <LightCTA />
        <AboutFAQs />
        <SplitContact />
    </main>
  }