import { Inter, Asap, Poppins } from 'next/font/google'
import './globals.css'
import mainHeader from '../app/components/headers/mainHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <mainHeader />
        {children}
        </body>
    </html>
  )
}
