import { Inter, Asap, Poppins } from 'next/font/google'
import './globals.css'
import Footer from './components/footers/footer'
import Header from './components/headers/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />

        <script src="./node_modules/preline/dist/preline.js"></script>
        </body>
    </html>
  )
}
