export const metadata = {
    title: 'Case Studies',
    description: 'Generated by create next app',
}

export default function Page() {
    return <main>
        <h1>Hello, Case Studies</h1>
    </main>
  }